apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-static-egress-controller
  namespace: kube-system
  labels:
    application: kube-static-egress-controller
    version: v0.1.7
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-static-egress-controller
  template:
    metadata:
      labels:
        application: kube-static-egress-controller
        version: v0.1.7
      annotations:
        iam.amazonaws.com/role: "{{ .LocalID }}-static-egress-controller"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-cluster-critical
      containers:
      - name: controller
        image: registry.opensource.zalan.do/teapot/kube-static-egress-controller:v0.1.7
        args:
        - "--provider=aws"
{{- range $subnet := stupsNATSubnets .Values.vpc_ipv4_cidr }}
        - "--aws-nat-cidr-block={{ $subnet }}"
{{- end }}
{{ range $zone := .Values.availability_zones }}
        - "--aws-az={{ $zone }}"
{{ end }}
        - "--stack-termination-protection"
        env:
        - name: AWS_REGION
          value: eu-central-1
        resources:
          limits:
            cpu: 5m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 50Mi
